[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os
sqlalchemy.url = postgresql://farmflow:farmflow@localhost:5432/farmflow

# Log output from batch operations
# batch_log_output = screen

# Additional arguments for 'engine_from_config'
# engine_opts = pool_pre_ping=True

# set this to 'true' to run the environment during
# migration, to allow the application to be introspected
# when the migration is run. If you usually work in
# debug / development mode, this should be set to true.
# run_env_during_migration = true

# Log level
# verbose_logging = true

# version table name
# version_table = alembic_version

# type of migration to generate
# migration_type = standard

# the output encoding used when writing files
# output_encoding = utf-8

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
