export const moduleCategories = [
  {
    code: 'socle',
    label: 'Socle ERP',
    description: 'Pilotage, configuration, roles, automatisations et supervision globale.',
  },
  {
    code: 'production',
    label: 'Production agricole',
    description: 'Parcelles, cultures, elevage, interventions et donnees terrain.',
  },
  {
    code: 'operations',
    label: 'Operations',
    description: 'Stocks, materiel, RH, planning, temps et disponibilites.',
  },
  {
    code: 'commerce',
    label: 'Commerce',
    description: 'Achats, fournisseurs, ventes, caisse, clients et circuits courts.',
  },
  {
    code: 'finance',
    label: 'Finance',
    description: 'Comptabilite, banque, tresorerie, marges et prix de revient.',
  },
  {
    code: 'conformite',
    label: 'Conformite',
    description: 'Exports, documents, audit, TVA, FEC et tracabilite.',
  },
  {
    code: 'plateforme',
    label: 'Plateforme',
    description: 'IA, communication, connecteurs, webhooks et IoT.',
  },
]

export const farmflowApps = [
  {
    code: 'pilotage',
    name: 'Pilotage ferme',
    category: 'socle',
    route: '/',
    status: 'socle pret',
    priority: 'haute',
    description: 'Cockpit dirigeant pour suivre production, marges, tresorerie, alertes et obligations.',
    capabilities: ['tableau de bord', 'alertes', 'objectifs', 'vues par atelier'],
    firstActions: ['Configurer les ateliers', 'Choisir les modules actifs', 'Definir les roles'],
    endpoints: ['GET /pilotage/dashboard', 'GET /pilotage/apps', 'GET /pilotage/workflows'],
  },
  {
    code: 'parcelles',
    name: 'Parcelles',
    category: 'production',
    route: '/parcelles',
    status: 'socle disponible',
    priority: 'haute',
    description: 'Cadastre agricole, ilots, cultures, sols, surfaces, rotations et cartographie.',
    capabilities: ['fiche parcelle', 'rotation', 'sols', 'historique cultural'],
    firstActions: ['Importer les ilots', 'Renseigner surfaces', 'Associer cultures en cours'],
    endpoints: ['GET /parcelles/', 'POST /parcelles/', 'GET /parcelles/{id}/cultures'],
  },
  {
    code: 'cultures-interventions',
    name: 'Cultures & interventions',
    category: 'production',
    route: '/chantiers',
    status: 'a enrichir',
    priority: 'haute',
    description: 'Itineraires techniques, interventions, temps de travaux, intrants, IFT et couts terrain.',
    capabilities: ['planning cultural', 'interventions', 'IFT', 'temps et couts'],
    firstActions: ['Creer les itineraires', 'Planifier les interventions', 'Lier stocks et materiel'],
    endpoints: ['GET /chantiers/', 'GET /parcelles/{id}/interventions', 'GET /export/parcelles/csv'],
  },
  {
    code: 'elevage',
    name: 'Elevage',
    category: 'production',
    route: '/animaux',
    status: 'socle disponible',
    priority: 'haute',
    description: 'Troupeaux, identification, reproduction, sanitaire, lots, mouvements et performances.',
    capabilities: ['animaux', 'lots', 'sanitaire', 'reproduction', 'RFID'],
    firstActions: ['Importer les animaux', 'Creer les lots', 'Planifier les suivis sanitaires'],
    endpoints: ['GET /animaux/', 'POST /animaux/', 'GET /animaux/{id}/sante'],
  },
  {
    code: 'stocks',
    name: 'Stocks',
    category: 'operations',
    route: '/stocks',
    status: 'socle disponible',
    priority: 'haute',
    description: 'Intrants, aliments, produits finis, lots, seuils, mouvements et valorisation.',
    capabilities: ['seuils', 'lots', 'mouvements', 'valorisation', 'liaison interventions'],
    firstActions: ['Creer les categories', 'Saisir stocks initiaux', "Definir les seuils d'alerte"],
    endpoints: ['GET /stocks', 'GET /stocks/categories', 'GET /export/stocks/csv'],
  },
  {
    code: 'achats',
    name: 'Achats fournisseurs',
    category: 'commerce',
    route: '/apps/achats',
    status: 'a construire',
    priority: 'haute',
    description: 'Demandes de prix, commandes, receptions, factures fournisseurs et couts par atelier.',
    capabilities: ['devis', 'commandes', 'receptions', 'factures', 'couts imputes'],
    firstActions: ['Structurer fournisseurs', 'Creer modeles de commande', 'Lier factures et stocks'],
    endpoints: ['POST /achats/commandes', 'GET /achats/fournisseurs', 'POST /comptabilite/ecritures'],
  },
  {
    code: 'ventes-caisse',
    name: 'Ventes & caisse',
    category: 'commerce',
    route: '/ventes',
    status: 'socle disponible',
    priority: 'haute',
    description: 'Devis, factures, ventes directes, tickets, paniers, marches et clotures de caisse.',
    capabilities: ['devis', 'factures', 'tickets', 'paiements', 'cloture journaliere'],
    firstActions: ['Configurer produits', 'Creer moyens de paiement', 'Activer journal de caisse'],
    endpoints: ['GET /ventes', 'GET /pilotage/caisse', 'GET /export/ventes/csv'],
  },
  {
    code: 'crm',
    name: 'CRM agricole',
    category: 'commerce',
    route: '/crm',
    status: 'socle disponible',
    priority: 'moyenne',
    description: 'Clients, prospects, distributeurs, circuits courts, contrats et historique commercial.',
    capabilities: ['contacts', 'segments', 'opportunites', 'contrats', 'relances'],
    firstActions: ['Importer clients', 'Segmenter circuits', 'Creer pipelines de vente'],
    endpoints: ['GET /crm/clients', 'POST /crm/prospects', 'GET /crm/opportunites'],
  },
  {
    code: 'comptabilite',
    name: 'Comptabilite',
    category: 'finance',
    route: '/comptabilite',
    status: 'socle disponible',
    priority: 'haute',
    description: 'Journaux, plan comptable agricole, ecritures, TVA, immobilisations et clotures.',
    capabilities: ['journaux', 'ecritures', 'TVA', 'immobilisations', 'cloture'],
    firstActions: ['Definir exercice', 'Configurer journaux', 'Importer plan comptable'],
    endpoints: ['GET /comptabilite', 'POST /comptabilite/ecritures', 'GET /pilotage/exports/reglementaires'],
  },
  {
    code: 'banque-tresorerie',
    name: 'Banque & tresorerie',
    category: 'finance',
    route: '/apps/banque-tresorerie',
    status: 'connecteur a brancher',
    priority: 'haute',
    description: 'Synchronisation bancaire, rapprochement, prevision de tresorerie et alertes de flux.',
    capabilities: ['synchro bancaire', 'rapprochement', 'categorisation', 'prevision', 'alertes'],
    firstActions: ['Choisir connecteur', 'Importer historique', 'Definir seuils de tresorerie'],
    endpoints: ['GET /pilotage/banque', 'POST /pilotage/banque/analyser-flux'],
  },
  {
    code: 'marges',
    name: 'Marges & prix de revient',
    category: 'finance',
    route: '/apps/marges',
    status: 'simulateur pret',
    priority: 'haute',
    description: 'Marge brute par culture, lot animal, produit, canal, seuils et scenarios de prix.',
    capabilities: ['marge brute', 'prix de revient', 'budget/reel', 'seuil', 'scenario'],
    firstActions: ['Definir ateliers', 'Imputer charges', 'Comparer budget et realise'],
    endpoints: ['GET /pilotage/marges', 'POST /pilotage/marges/simuler'],
  },
  {
    code: 'flotte-materiel',
    name: 'Flotte & materiel',
    category: 'operations',
    route: '/flotte',
    status: 'socle disponible',
    priority: 'moyenne',
    description: 'Tracteurs, outils, entretiens, carburant, cout horaire et disponibilite chantier.',
    capabilities: ['vehicules', 'entretiens', 'carburant', 'cout horaire', 'planning'],
    firstActions: ['Inventorier materiel', 'Programmer entretiens', 'Calculer couts horaires'],
    endpoints: ['GET /flotte', 'POST /flotte/entretiens', 'GET /chantiers'],
  },
  {
    code: 'rh',
    name: 'RH & planning',
    category: 'operations',
    route: '/rh',
    status: 'socle disponible',
    priority: 'moyenne',
    description: 'Saisonniers, permanents, temps de travaux, competences, absences et paie preparatoire.',
    capabilities: ['employes', 'planning', 'temps', 'absences', 'paie'],
    firstActions: ['Creer equipes', 'Declarer competences', 'Lier temps aux chantiers'],
    endpoints: ['GET /rh/employes', 'GET /rh/conges', 'POST /rh/planning'],
  },
  {
    code: 'calendrier',
    name: 'Calendrier agricole',
    category: 'operations',
    route: '/calendrier',
    status: 'socle disponible',
    priority: 'moyenne',
    description: 'Evenements, rappels, fenetres meteo, taches recurrentes et echeances reglementaires.',
    capabilities: ['agenda', 'rappels', 'echeances', 'meteo', 'recurrence'],
    firstActions: ['Importer echeances', 'Planifier cultures', 'Activer rappels'],
    endpoints: ['GET /calendrier', 'POST /calendrier/evenements'],
  },
  {
    code: 'documents-reglementaire',
    name: 'Documents & reglementaire',
    category: 'conformite',
    route: '/apps/documents-reglementaire',
    status: 'exports prets',
    priority: 'haute',
    description: 'FEC, journaux, grand livre, balance, TVA, tracabilite technique et pieces justificatives.',
    capabilities: ['FEC', 'journaux', 'grand livre', 'balance', 'tracabilite', 'audit'],
    firstActions: ['Parametrer exercice', 'Centraliser justificatifs', 'Tester exports'],
    endpoints: ['GET /pilotage/exports/reglementaires', 'GET /export/comptabilite/csv'],
  },
  {
    code: 'ia-agricole',
    name: 'IA agricole',
    category: 'plateforme',
    route: '/ia',
    status: 'connecteur a brancher',
    priority: 'moyenne',
    description: 'Assistant contextualise, OCR factures, anomalies, recommandations et syntheses de ferme.',
    capabilities: ['assistant', 'OCR', 'anomalies', 'recommandations', 'syntheses'],
    firstActions: ['Choisir modele', 'Definir donnees autorisees', "Activer journal d'audit"],
    endpoints: ['GET /pilotage/ia/preparation', 'POST /ia/analyser'],
  },
  {
    code: 'communication',
    name: 'Communication',
    category: 'plateforme',
    route: '/communication',
    status: 'socle disponible',
    priority: 'basse',
    description: 'Email, SMS, WhatsApp, campagnes clients, alertes internes et notifications equipe.',
    capabilities: ['campagnes', 'notifications', 'SMS', 'email', 'WhatsApp'],
    firstActions: ['Configurer canaux', 'Creer modeles', 'Segmenter destinataires'],
    endpoints: ['GET /communication/campagnes', 'POST /communication/envoyer'],
  },
  {
    code: 'integrations',
    name: 'Integrations & automatisations',
    category: 'plateforme',
    route: '/apps/integrations',
    status: 'socle zapier',
    priority: 'moyenne',
    description: 'Zapier, API meteo, paiement, code-barres, etiquettes, IoT et connecteurs externes.',
    capabilities: ['Zapier', 'meteo', 'paiement', 'code-barres', 'IoT', 'webhooks'],
    firstActions: ['Lister connecteurs', 'Securiser webhooks', 'Prioriser automatisations'],
    endpoints: ['GET /zapier/triggers', 'POST /zapier/webhook'],
  },
]

export const workflows = [
  {
    code: 'intervention-culture-stock-marge',
    title: 'Intervention terrain -> stock -> marge',
    modules: ['parcelles', 'cultures-interventions', 'stocks', 'flotte-materiel', 'marges'],
    description: 'Une intervention consomme intrants, materiel et temps, puis alimente le cout de revient.',
    steps: ['Planifier', 'Affecter', 'Sortir intrants', 'Valider terrain', 'Actualiser marge'],
  },
  {
    code: 'vente-directe-caisse-compta-stock',
    title: 'Vente directe -> caisse -> compta -> stock',
    modules: ['ventes-caisse', 'stocks', 'crm', 'comptabilite', 'banque-tresorerie'],
    description: 'Une vente cree ticket, paiement, mouvement de stock et ecriture comptable.',
    steps: ['Composer panier', 'Encaisser', 'Cloturer', 'Generer ecritures', 'Rapprocher'],
  },
  {
    code: 'achat-intrant-banque-stock',
    title: 'Achat intrant -> reception -> banque -> cout atelier',
    modules: ['achats', 'stocks', 'comptabilite', 'banque-tresorerie', 'marges'],
    description: 'Les achats alimentent stocks, factures fournisseurs et couts des ateliers.',
    steps: ['Demande de prix', 'Commande', 'Reception', 'Facture', 'Paiement', 'Imputation'],
  },
  {
    code: 'elevage-sante-lot-marge',
    title: 'Elevage -> sanitaire -> lot -> marge',
    modules: ['elevage', 'stocks', 'calendrier', 'marges', 'documents-reglementaire'],
    description: 'Les soins, aliments, mouvements et ventes structurent la marge par lot.',
    steps: ['Identifier', 'Planifier soin', 'Consommer stock', 'Suivre lot', 'Calculer marge'],
  },
  {
    code: 'cloture-reglementaire',
    title: 'Cloture -> exports -> expert-comptable',
    modules: ['comptabilite', 'documents-reglementaire', 'banque-tresorerie', 'pilotage'],
    description: 'La cloture consolide pieces, journaux, TVA, FEC, balances et anomalies.',
    steps: ['Controler pieces', 'Rapprocher banque', 'Calculer TVA', 'Exporter', 'Archiver'],
  },
]

export const roles = [
  { code: 'exploitant', name: 'Exploitant', level: 'admin', focus: 'decision, marges, tresorerie, clotures' },
  { code: 'chef-culture', name: 'Chef de culture', level: 'manager', focus: 'interventions, IFT, intrants' },
  { code: 'responsable-elevage', name: 'Responsable elevage', level: 'manager', focus: 'troupeau, sanitaire, lots' },
  { code: 'commercial-caisse', name: 'Commercial / caisse', level: 'operationnel', focus: 'ventes, encaissements, clients' },
  { code: 'comptable', name: 'Comptable', level: 'controle', focus: 'banque, TVA, exports, pieces' },
  { code: 'salarie-terrain', name: 'Salarie terrain', level: 'saisie', focus: 'taches, temps, observations' },
]

export const categoryByCode = moduleCategories.reduce((acc, category) => {
  acc[category.code] = category
  return acc
}, {})

export const appByCode = farmflowApps.reduce((acc, app) => {
  acc[app.code] = app
  return acc
}, {})

export const getAppByCode = (code) => appByCode[code]

export const groupAppsByCategory = (apps = farmflowApps) => moduleCategories
  .map((category) => ({
    ...category,
    apps: apps.filter((app) => app.category === category.code),
  }))
  .filter((category) => category.apps.length > 0)
